EMAIL_USE_TLS=True
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER='singhivjots13@gmail.com'
EMAIL_HOST_PASSWORD='a'
EMAIL_PORT=587
#SENDGRID_API_KEY="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"
SENDGRID_API_KEY="lol"