# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20170727_1250'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='User_model',
        ),
    ]
