# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0004_auto_20170727_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionToken_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sessionToken', models.CharField(max_length=100)),
                ('is_valid', models.BooleanField(default=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('lastAccessed_on', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.User_model')),
            ],
        ),
    ]
