# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 11:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0006_post_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_model',
            name='image_url',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
