# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0007_post_model_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='post_model',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post_model',
            name='image',
            field=models.FileField(upload_to='user_images'),
        ),
        migrations.AddField(
            model_name='like_model',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Post_model'),
        ),
        migrations.AddField(
            model_name='like_model',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.User_model'),
        ),
    ]
