# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_auto_20170801_0023'),
    ]

    operations = [
        migrations.CreateModel(
            name='HashModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.PostModel')),
            ],
        ),
    ]
