# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_hashmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hashmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='tag',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='social.HashModel'),
            preserve_default=False,
        ),
    ]
