# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-02 20:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_auto_20170803_0120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hashmodel',
            old_name='tag',
            new_name='HASH',
        ),
    ]
