# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-03 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0013_auto_20170803_0140'),
    ]

    operations = [
        migrations.CreateModel(
            name='FetchModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='postmodel',
            name='tag',
        ),
        migrations.DeleteModel(
            name='HashModel',
        ),
        migrations.AddField(
            model_name='fetchmodel',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.PostModel'),
        ),
        migrations.AddField(
            model_name='fetchmodel',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.TagModel'),
        ),
    ]
