# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_auto_20170804_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='has_upvoted',
            field=models.BooleanField(default=False),
        ),
    ]
