# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0018_commentmodel_has_upvoted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentmodel',
            name='has_upvoted',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='recommend',
            field=models.BooleanField(default=False),
        ),
    ]
