# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0019_auto_20170804_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='recommend',
        ),
    ]
