# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_remove_postmodel_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='has_liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='has_recommended',
            field=models.BooleanField(default=False),
        ),
    ]
