# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 12:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_auto_20170804_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='name',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(b'^[a-zA-Z ]{3,40}$')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(b'[A-Za-z0-9@#$%^&+=]{8,}')]),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=120, validators=[django.core.validators.RegexValidator(b'^[a-zA-Z 0-9_-]{3,40}$')]),
        ),
    ]
