# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 18:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0022_auto_20170808_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.CharField(max_length=40, validators=[django.core.validators.RegexValidator(b'^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[$@$!%*?&])[A-Za-z\\d$@$!%*?&]{8,10}$')]),
        ),
    ]
